function h = drawSVMPredictions(Z, Yhat, algolabel)

cpt = {'BAD','GOOD'};
h = zeros(1,2);
if sum(Yhat==0)~=0
    h(1) = line(Z(Yhat==0,1), Z(Yhat==0,2), 'LineStyle', 'none', ...
                                            'Marker', 'o', ...
                                            'Color', [0.8 0.8 0.8], ...
                                            'MarkerFaceColor', [0.8 0.8 0.8], ...
                                            'MarkerSize', 6);
end
if sum(Yhat==1)~=0
    h(2) = line(Z(Yhat==1,1), Z(Yhat==1,2), 'LineStyle', 'none', ...
                                            'Marker', 'o', ...
                                            'Color', [0.0 0.0 0.0], ...
                                            'MarkerFaceColor', [0.0 0.0 0.0], ...
                                            'MarkerSize', 6);
end
xlabel('z_{1}'); ylabel('z_{2}'); title(algolabel);
legend(h(h~=0), cpt(h~=0), 'Location', 'NorthEastOutside');
set(findall(gcf,'-property','FontSize'),'FontSize',12);
set(findall(gcf,'-property','LineWidth'),'LineWidth',1);
axis square;