% -------------------------------------------------------------------------
% webscript.m
% -------------------------------------------------------------------------
%
% By: Mario Andres Munoz Acosta
%     School of Mathematics and Statistics
%     The University of Melbourne
%     Australia
%     2020
%
% -------------------------------------------------------------------------

disp('=========================================================================');
disp('-> Writing the data for the web interfase.');
% -------------------------------------------------------------------------
writetable(array2table(parula(256), ...
           'VariableNames', {'R','G','B'}), ...
           [rootdir 'color_table.csv']);
writeArray2CSV(colorscale(model.data.Xraw(:,model.featsel.idx)), ...
               model.data.featlabels, ...
               model.data.instlabels, ...
               [rootdir 'feature_raw_color.csv']);
writeArray2CSV(colorscale(model.data.Yraw), ...
               model.data.algolabels, ...
               model.data.instlabels, ...
               [rootdir 'algorithm_raw_single_color.csv']);
writeArray2CSV(colorscale(model.data.X), ...
               model.data.featlabels, ...
               model.data.instlabels, ...
               [rootdir 'feature_process_color.csv']);
writeArray2CSV(colorscale(model.data.Y), ...
               model.data.algolabels, ...
               model.data.instlabels, ...
               [rootdir 'algorithm_process_single_color.csv']);
writeArray2CSV(colorscaleg(model.data.Yraw), ...
               model.data.algolabels, ...
               model.data.instlabels, ...
               [rootdir 'algorithm_raw_color.csv']);
writeArray2CSV(colorscaleg(model.data.Y), ...
               model.data.algolabels, ...
               model.data.instlabels, ...
               [rootdir 'algorithm_process_color.csv']);
writeArray2CSV(colorscaleg(model.data.numGoodAlgos),  ...
               {'NumGoodAlgos'}, ...
               model.data.instlabels, ...
               [rootdir 'good_algos_color.csv']);